export const categoryData = [
  { id: 1, category_name: "Electronics" },
  { id: 2, category_name: "Books" },
  { id: 3, category_name: "Clothing" },
  { id: 4, category_name: "Home & Kitchen" },
  { id: 5, category_name: "Toys & Games" },
  { id: 6, category_name: "Sports & Outdoors" },
  { id: 7, category_name: "Health & Beauty" },
  { id: 8, category_name: "Automotive" },
  { id: 9, category_name: "Jewelry" },
  { id: 10, category_name: "Music & Audio" },
  { id: 11, category_name: "Garden & Outdoor" },
  { id: 12, category_name: "Pet Supplies" },
  { id: 13, category_name: "Computers" },
  { id: 14, category_name: "Office Supplies" },
  { id: 15, category_name: "Grocery" },
  { id: 16, category_name: "Footwear" },
  { id: 17, category_name: "Bags & Luggage" },
  { id: 18, category_name: "Toys & Games" },
  { id: 19, category_name: "Baby Products" },
  { id: 20, category_name: "Personal Care Appliances" },
];
